apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mskafka-postgres
  name: postgres
  namespace: store
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: mskafka-postgres
  type: ClusterIP
status:
  loadBalancer: {}
