apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mskafka-order
  name: mskafka-order
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mskafka-order
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mskafka-order
    spec:
      containers:
      - image: prasta/mskafka_order
        name: mskafka-order
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-addr
              key: kafka_addr
