apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mskafka-invoicing
  name: invoicing
  namespace: store
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mskafka-invoicing
  type: ClusterIP
status:
  loadBalancer: {}
