apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mskafka-shipping
  name: shipping
  namespace: store
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mskafka-shipping
  type: ClusterIP
status:
  loadBalancer: {}
